# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.IntegerField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=200)),
                ('projectProgress', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.IntegerField(primary_key=True)),
                ('projectID', models.IntegerField(primary_key=True, serialize=False)),
                ('taskState', models.CharField(choices=[('AW', 'awaiting'), ('IP', 'In Progress'), ('CP', 'Completed')], default='AW', max_length=200)),
                ('taskCompletion', models.BooleanField(default=False)),
                ('difficultyLevel', models.CharField(max_length=30)),
                ('expectedDate', models.DateField()),
                ('actualDate', models.DateField()),
                ('daysLeft', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='projectTasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Task'),
        ),
        migrations.AddField(
            model_name='project',
            name='teamMembers',
            field=models.ManyToManyField(related_name='my_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
