# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='projectID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
