# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_projecttasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficultyLevel',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult')], default='E', max_length=200),
        ),
    ]
