# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20160415_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='teamMembers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='projectID',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
