# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20160410_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('female.png', 'female1'), ('female2.png', 'female2'), ('male.png', 'male1'), ('male2.png', 'male2')], max_length=200, null=True),
        ),
    ]
