# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('female2.png', 'Female'), ('male2.png', 'Male')], max_length=200, null=True),
        ),
    ]
