# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20160409_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='withYou',
            field=models.IntegerField(default=0),
        ),
    ]
