# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160415_2322'),
        ('discussion', '0003_auto_20160409_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.Project'),
        ),
    ]
