# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_post_withyou'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isWithYou',
            field=models.BooleanField(default=False),
        ),
    ]
