# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 17:20
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200, unique=True)),
                ('projectProgress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('dueDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200)),
                ('taskState', models.CharField(choices=[('AW', 'Awaiting'), ('IP', 'In Progress'), ('CP', 'Completed')], default='AW', max_length=200)),
                ('difficultyLevel', models.CharField(choices=[(1, 'Easy'), (3, 'Medium'), (5, 'Difficult')], default=1, max_length=200)),
                ('expectedDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('actualDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
