# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficultyLevel',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult')], default='E', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='taskCompletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='taskState',
            field=models.CharField(choices=[('AW', 'awaiting'), ('IP', 'In Progress'), ('CP', 'Completed')], default='AW', max_length=200),
        ),
    ]
