# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160415_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskCompletion',
            new_name='completed',
        ),
    ]
