# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160415_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
