# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160420_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='difficultyLevel',
            field=models.CharField(choices=[(1, 'Easy'), (3, 'Medium'), (5, 'Difficult')], default=1, max_length=200),
        ),
    ]
