# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160420_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(default='Untitled Project', max_length=200, unique=True),
        ),
    ]
