# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160424_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dueDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
