# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20160505_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grabBy',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
