# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_grabby'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskProgress',
            field=models.IntegerField(default=0),
        ),
    ]
