# -*- coding: utf-8 -*-

# Generated by Django 1.9.1 on 2016-05-07 07:20

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_grabby'),
        ('schedule1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingName', models.CharField(max_length=500)),
                ('meetingAgenda', models.CharField(max_length=1000)),
                ('meetingSummary', models.CharField(max_length=1000)),
                ('meetingDate', models.DateField(default=django.utils.timezone.now)),
                ('meetingStatus', models.CharField(choices=[('CF', 'Confirm'), ('RJ', 'Reject')], max_length=200)),
                ('confirmedCount', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
