# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule1', '0002_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meetingStatus',
            field=models.CharField(choices=[('CF', 'Confirm'), ('RJ', 'Reject'), ('PD', 'Pending')], max_length=200),
        ),
    ]
