# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratePeer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='total',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
