# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20160425_1736'),
        ('ratePeer', '0002_rating_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating1',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating2',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5, max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating3',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5, max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating4',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5, max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating5',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5, max_length=200),
        ),
    ]
